// THIS IS AUTOGENERATED CODE FOR VISION TARGETS WRITTEN IN MATLAB
// This file was auto-generated by Matlab under the supervision of Jacob Krucinski on 16-Mar-2019 at 11:07
#define H_min      62.0313
#define H_max      81.6667
#define S_min     110.1240
#define S_max     255.0000
#define V_min      44.0000
#define V_max     255.0000
