// THIS IS AUTOGENERATED CODE FOR VISION TARGETS WRITTEN IN MATLAB
// This file was auto-generated by Matlab under the supervision of Jacob Krucinski on 19-Mar-2019 at 18:20
#define H_min       0.0000
#define H_max     155.0000
#define S_min       0.0000
#define S_max      25.0682
#define V_min     198.0000
#define V_max     255.0000
