// THIS IS AUTOGENERATED CODE FOR VISION TARGETS WRITTEN IN MATLAB
// This file was auto-generated by Matlab under the supervision of Jacob Krucinski on 16-Mar-2019 at 10:15
#define h      18.5000
#define w       6.0000
#define area     110.5000
#define H      74.9390
#define S     203.9942
#define V     250.6061
