// THIS IS AUTOGENERATED CODE FOR VISION TARGETS WRITTEN IN MATLAB
// This file was auto-generated by Matlab under the supervision of Jacob Krucinski on 29-Mar-2019 at 19:52
#define H_min      55.8696
#define H_max      71.5625
#define S_min      97.9730
#define S_max     255.0000
#define V_min      86.0000
#define V_max     201.0000
