// THIS IS AUTOGENERATED CODE FOR VISION TARGETS WRITTEN IN MATLAB
// This file was auto-generated by Matlab under the supervision of Jacob Krucinski on 16-Mar-2019 at 09:47
#define h      17.0000
#define w       5.0000
#define area      85.0000
#define H      75.0839
#define S     207.5965
#define V     175.8835
